site_name: Algobattle
site_description: Algobattle framework, an interactive, easy to use computer science lab course
repo_name: benezivas/algobattle
repo_url: https://github.com/Benezivas/algobattle
edit_uri: ""

plugins:
  - search

theme:
  name: material

  icon:
    repo: fontawesome/brands/github

  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: indigo
    accent: amber
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode

  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: indigo
    accent: amber
    toggle:
      icon: material/weather-night
      name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
  language: en

nav:
  - Algobattle: index.md
  - Student Guide:
    - student/index.md
  - Instructor Guide:
    - instructor/index.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.admonition

extra_css:
  - css/termynal.css

extra_javascript:
  - js/termynal.js

