[build-system]
requires = ["uv_build>=0.12.17,<0.13"]
build-backend = "uv_build"

[project]
name = "algobattle-base"
version = "4.3.5"
description = "The Algobattle lab course package."
readme = "README.md"
requires-python = ">=3.14"
license = { text = "MIT" }
authors = [
    { name = "Imogen Hergeth" },
    { name = "Jan Dreier" },
    { name = "Henri Lotze" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Natural Language :: English",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Typing :: Typed",
]
dependencies = [
    "docker>=7.2.0",
    "pydantic>=2.13.5",
    "anyio>=4.15.1",
    "typer>=0.27.2",
    "typing-extensions>=4.16.0",
    "tomlkit>=0.15.1",
    "jinja2>=3.1.6",
]
import-names = ["algobattle"]

[project.urls]
Homepage = "https://algobattle.org"
Documentation = "https://algobattle.org/docs"
Repository = "https://github.com/Benezivas/algobattle"

[project.scripts]
algobattle = "algobattle.cli:app"

[dependency-groups]
dev = [
    "ruff>=0.16.8",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.7",
    "pymdown-extensions>=12.0.1",
    "mkdocstrings[python]>=1.0.6",
    "mdx-include>=1.4.2",
]


[tool.uv.build-backend]
module-name = "algobattle"

[tool.ruff]
preview = true
line-length = 120
exclude = ["docs/src"]

[tool.ruff.lint]
select = [
    "F",
    "E4",
    "E7",
    "E9",
    "I",
    "UP",
    "YTT",
    "ASYNC",
    "BLE",
    "FBT",
    "B",
    "C4",
    "DTZ",
    "ISC",
    "G",
    "PIE",
    "PYI",
    "SLOT",
    "SIM",
    "PTH",
    "TRY",
    "FLY",
    "PERF",
    "FURB",
    "RUF",
]
ignore = [
    "raise-vanilla-args",
    "unnecessary-placeholder",
    "boolean-type-hint-positional-argument",
    "boolean-default-value-positional-argument",
    "empty-method-without-abstract-decorator",
    "boolean-positional-value-in-call",
    "ambiguous-unicode-character-string",
    "none-not-at-end-of-union",
    "blind-except",
    "call-datetime-now-without-tzinfo",
    "async-function-with-timeout",
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false
combine-as-imports = true

[tool.pyright]
exclude = [".venv", "docs", "**/node_modules", "**/__pycache__", "**/.*"]
typeCheckingMode = "standard"
disableBytesTypePromotions = true
strictDictionaryInference = true
strictListInference = true
strictSetInference = true
deprecateTypingAliases = true
enableExperimentalFeatures = true
reportAssertAlwaysTrue = "information"
reportUnusedExpression = "information"
reportConstantRedefinition = "warning"
reportDeprecated = "information"
reportDuplicateImport = "information"
reportIncompleteStub = "warning"
reportInconsistentConstructor = "error"
reportInvalidStubStatement = "warning"
reportMatchNotExhaustive = "warning"
reportMissingParameterType = "warning"
reportMissingTypeArgument = "none"
reportPrivateUsage = "none"
reportTypeCommentUsage = "information"
reportUnknownArgumentType = "none"
reportUnknownLambdaType = "none"
reportUnknownMemberType = "none"
reportUnknownParameterType = "warning"
reportUnknownVariableType = "none"
reportUnnecessaryCast = "information"
reportUnnecessaryIsInstance = "information"
reportUnnecessaryComparison = "information"
reportUnnecessaryContains = "information"
reportUnusedCoroutine = "warning"
reportUntypedFunctionDecorator = "warning"
reportUntypedClassDecorator = "warning"
reportUntypedBaseClass = "warning"
reportUntypedNamedTuple = "warning"
reportCallInDefaultInitializer = "none"
reportImportCycles = "warning"
reportPropertyTypeMismatch = "error"
reportShadowedImports = "warning"
reportUnnecessaryTypeIgnoreComment = "information"
reportUninitializedInstanceVariable = "warning"
reportFunctionMemberAccess = "warning"
reportOverlappingOverload = "warning"
