[project]
name = "algobattle"
version = "4.0.0"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [{name = "Imogen Hergeth"}, {name = "Jan Dreier"}, {name = "Henri Lotze"}]
urls = {github = "https://github.com/Benezivas/algobattle"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Natural Language :: English",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Typing :: Typed",
]
dependencies = [
    "docker>=6.1.2",
    "prettytable>=3.7.0",
    "pydantic~=1.10",
    "anyio>=3.6.2",
    # on windows, we need to manually install curses bindings
    "windows-curses>=2.3.1; os_name == 'nt'",
]

[project.scripts]
algobattle = "algobattle.cli:main"

[tool.pyright]
diagnosticMode = "workspace"

[tool.black]
line-length = 120
