[project]
name = "algobattle"
version = "4.0.0"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [{name = "Imogen Hergeth"}, {name = "Jan Dreier"}, {name = "Henri Lotze"}]
urls = {github = "https://github.com/Benezivas/algobattle"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Natural Language :: English",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Typing :: Typed",
]
dependencies = [
    "docker",
    "prettytable",
    "pydantic < 2",
    "anyio",

    # on windows, we need to manually install curses bindings
    "windows-curses; os_name == 'nt'",
]
[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "flake8-docstrings",
    "mkdocs",
    "mkdocs-material",
    "pymdown-extensions",
    "mkdocstrings[python]",
    "mdx_include",
]

[project.scripts]
algobattle = "algobattle.cli:main"

[tool.pyright]
diagnosticMode = "workspace"

[tool.black]
line-length = 120
