battle_type = "Iterated"
points = 100
parallel_battles = 1
mode = "tournament"
teams = []

[docker]
build_timeout = 300
strict_timeouts = false
image_size = 0
set_cpus = ""
advanced_build_params = {}
advanced_run_params = {}

[docker.generator]
timeout = 30
space = 0
cpus = 1

[docker.solver]
timeout = 30
space = 0
cpus = 1

[battle.Iterated]
rounds = 5
iteration_cap = 50_000
exponent = 2
approximation_ratio = 1

[battle.Averaged]
instance_size = 10
iterations = 10
