# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Algorithmic Battle

on:
  push:
    branches: [ main, develop, 4.0.0-rc ]
  pull_request:
    branches: [ main, develop, 4.0.0-rc ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-docstrings
    - name: Lint with flake8
      run: flake8 .

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: install Docker
      if: runner.os == 'macOS'
      uses: docker-practice/actions-setup-docker@master
    - name: setup windows base image
      if: runner.os == 'Windows'
      run: |
        docker image tag mcr.microsoft.com/windows/nanoserver:ltsc2022 windows-base
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . --user
    - name: Test using unittests
      run: python -m unittest --failfast
